// src/main.cpp
//
// Crochet Stitch Detector -- ESP32 + LSM6DSOX + TFLite (INT8)
//
// Pipeline (mirrors Python training exactly):
//   1. Sample IMU at 100 Hz  ->  ax_g, ay_g, az_g, gx_dps, gy_dps, gz_dps
//   2. Accumulate 200 samples into a circular buffer (WINDOW_LENGTH)
//   3. Every 100 new samples (STRIDE):
//        a. Normalise: norm = (raw - mean) / std
//        b. Quantize:  int8 = clamp(round(norm / input_scale) + input_zp, -128, 127)
//        c. Run inference
//        d. Dequantize output: prob = (int8_out - output_zp) * output_scale
//   4. Print IMU readings + inference result to Serial
//
// If IMU reads all zeros, that means the sensor lost I2C contact.
// The [IMU ZERO] warning below will fire so you know to power-cycle
// without having to interpret raw numbers.

#include <Arduino.h>
#include <Wire.h>
#include <Adafruit_LSM6DSOX.h>
#include <TensorFlowLite_ESP32.h>
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/schema/schema_generated.h"

#include "model_data.h"   // generated by run_convert.py  (lives in include/)

// ---------------------------------------------------------------------------
// Configuration -- must match Python config.py
// ---------------------------------------------------------------------------

static const int   WINDOW_LENGTH  = 200;
static const int   STRIDE         = 100;
static const int   NUM_CHANNELS   = 6;
static const int   SAMPLE_RATE_HZ = 100;
static const float THRESHOLD      = 0.5f;

// ---------------------------------------------------------------------------
// Normalization constants -- from models/scaler/mean.npy and std.npy
// Order: [ax_g, ay_g, az_g, gx_dps, gy_dps, gz_dps]
// ---------------------------------------------------------------------------

static const float NORM_MEAN[NUM_CHANNELS] = {
  -0.16761149f,   // ax_g
  -0.67390168f,   // ay_g
   0.10533028f,   // az_g
  -0.25865123f,   // gx_dps
   1.07713866f,   // gy_dps
   0.82166719f    // gz_dps
};

static const float NORM_STD[NUM_CHANNELS] = {
   0.27730149f,   // ax_g
   0.34247386f,   // ay_g
   0.59229612f,   // az_g
  70.27664948f,   // gx_dps
  40.82910156f,   // gy_dps
  41.08145142f    // gz_dps
};

// ---------------------------------------------------------------------------
// INT8 quantization parameters -- from esp32_deployment_notes.txt
// Update these if you reconvert the model.
// ---------------------------------------------------------------------------

static const float INPUT_SCALE       =  0.03121445f;
static const int   INPUT_ZERO_POINT  = -4;
static const float OUTPUT_SCALE      =  0.00390625f;
static const int   OUTPUT_ZERO_POINT = -128;

// ---------------------------------------------------------------------------
// TFLite
// ---------------------------------------------------------------------------

static const int TENSOR_ARENA_SIZE = 60 * 1024;
static uint8_t   tensor_arena[TENSOR_ARENA_SIZE];

static tflite::MicroErrorReporter micro_error_reporter;
static tflite::ErrorReporter*     error_reporter  = &micro_error_reporter;
static const tflite::Model*       tfl_model       = nullptr;
static tflite::MicroInterpreter*  tfl_interpreter = nullptr;
static TfLiteTensor*              tfl_input       = nullptr;
static TfLiteTensor*              tfl_output      = nullptr;

// ---------------------------------------------------------------------------
// Sampling state
// ---------------------------------------------------------------------------

static float         sample_buf[WINDOW_LENGTH][NUM_CHANNELS];
static int           buf_head                     = 0;
static int           samples_in_buf               = 0;
static int           samples_since_last_inference  = 0;

// Most recent raw IMU values -- updated every sample, printed at inference time
static float last_ax = 0, last_ay = 0, last_az = 0;
static float last_gx = 0, last_gy = 0, last_gz = 0;

// ---------------------------------------------------------------------------
// Stitch counting + debounce
//
// Problem: one physical stitch spans ~300 samples but stride=100, so it
// shows up in 2-3 consecutive windows all above threshold.
//
// Solution: rising-edge detection + cooldown.
//   - Only count when transitioning from non-stitch -> stitch (rising edge).
//   - After counting, suppress for DEBOUNCE_WINDOWS windows so the tail
//     of the same motion can't re-trigger.
//
// DEBOUNCE_WINDOWS=2 means ~2s suppression after each count.
// Lower = more responsive but risks double-counts on slow stitches.
// ---------------------------------------------------------------------------

static const int DEBOUNCE_WINDOWS  = 1;
static int       stitch_count      = 0;
static int       debounce_remaining = 0;
static int       prev_prediction   = 0;

Adafruit_LSM6DSOX imu;

static unsigned long       last_sample_us     = 0;
static const unsigned long SAMPLE_INTERVAL_US = 1000000UL / SAMPLE_RATE_HZ;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static inline int8_t clamp_to_int8(float v) {
  if (v < -128.0f) return -128;
  if (v >  127.0f) return  127;
  return (int8_t) roundf(v);
}

// Normalise then quantize the circular buffer into the INT8 input tensor
void fill_quantize_input() {
  int8_t* input_data = tfl_input->data.int8;

  for (int i = 0; i < WINDOW_LENGTH; i++) {
    int src = (buf_head + i) % WINDOW_LENGTH;
    for (int ch = 0; ch < NUM_CHANNELS; ch++) {
      float norm      = (sample_buf[src][ch] - NORM_MEAN[ch]) / NORM_STD[ch];
      float quantized =  norm / INPUT_SCALE + INPUT_ZERO_POINT;
      input_data[i * NUM_CHANNELS + ch] = clamp_to_int8(quantized);
    }
  }
}

void run_inference() {
  fill_quantize_input();

  TfLiteStatus status = tfl_interpreter->Invoke();
  if (status != kTfLiteOk) {
    // Serial.println("[ERROR] Inference failed");
    return;
  }

  // Dequantize INT8 output -> probability [0, 1]
  int8_t raw_out    = tfl_output->data.int8[0];
  float  prob       = (raw_out - OUTPUT_ZERO_POINT) * OUTPUT_SCALE;
  int    prediction = (prob >= THRESHOLD) ? 1 : 0;

  // --- Rising-edge detection + debounce ---
  if (debounce_remaining > 0) debounce_remaining--;

  if (prediction == 1 && prev_prediction == 0 && debounce_remaining == 0) {
    stitch_count++;
    debounce_remaining = DEBOUNCE_WINDOWS;
    Serial.print(">>> STITCH DETECTED total=");
    Serial.println(stitch_count);
  }
  prev_prediction = prediction;

  // IMU zero warning
  bool imu_zero = (last_ax == 0.0f && last_ay == 0.0f && last_az == 0.0f &&
                   last_gx == 0.0f && last_gy == 0.0f && last_gz == 0.0f);
  if (imu_zero) Serial.println("<<< IMU ZERO - check wiring / power-cycle >>>");

  // Debug prints (uncomment to diagnose)
//  Serial.print("[IMU] ax="); Serial.print(last_ax, 3);
//  Serial.print(" ay=");      Serial.print(last_ay, 3);
//  Serial.print(" az=");      Serial.print(last_az, 3);
//  Serial.print(" | gx=");    Serial.print(last_gx, 1);
//  Serial.print(" gy=");      Serial.print(last_gy, 1);
//  Serial.print(" gz=");      Serial.print(last_gz, 1);
//  Serial.println();
//  Serial.print("[INF] prob=");  Serial.print(prob, 4);
//  Serial.print("  raw=");       Serial.print(raw_out);
//  Serial.print("  cooldown=");  Serial.print(debounce_remaining);
//  Serial.print("  stitches=");  Serial.println(stitch_count);
//  Serial.println();
}

// ---------------------------------------------------------------------------
// Setup
// ---------------------------------------------------------------------------

void setup() {
  Serial.begin(115200);
  while (!Serial) delay(10);

//   Serial.println("==============================");
//   Serial.println("Crochet Stitch Detector");
//   Serial.println("==============================");

  // --- IMU ---
//   Serial.print("[LOG] Initialising LSM6DSOX... ");
  if (!imu.begin_I2C()) {
    // Serial.println("FAILED");
    while (1) delay(10);
  }
  imu.setAccelRange(LSM6DS_ACCEL_RANGE_2_G);
  imu.setGyroRange(LSM6DS_GYRO_RANGE_250_DPS);
  imu.setAccelDataRate(LSM6DS_RATE_104_HZ);
  imu.setGyroDataRate(LSM6DS_RATE_104_HZ);
  Serial.println("OK");

  // --- TFLite model ---
//   Serial.print("[LOG] Loading TFLite model... ");
  tfl_model = tflite::GetModel(model_data);
  if (tfl_model->version() != TFLITE_SCHEMA_VERSION) {
    // Serial.println("FAILED - schema version mismatch");
    while (1) delay(10);
  }
//   Serial.println("OK");

  static tflite::AllOpsResolver resolver;
  static tflite::MicroInterpreter static_interpreter(
    tfl_model, resolver, tensor_arena, TENSOR_ARENA_SIZE, error_reporter
  );
  tfl_interpreter = &static_interpreter;

//   Serial.print("[LOG] Allocating tensors... ");
  if (tfl_interpreter->AllocateTensors() != kTfLiteOk) {
    // Serial.println("FAILED - try increasing TENSOR_ARENA_SIZE");
    while (1) delay(10);
  }
//   Serial.println("OK");

  tfl_input  = tfl_interpreter->input(0);
  tfl_output = tfl_interpreter->output(0);

  // Sanity checks -- these will tell you immediately if the wrong model was flashed
//   Serial.print("[LOG] Input  dtype: ");
//   Serial.println(tfl_input->type  == kTfLiteInt8 ? "int8 (correct)" : "WRONG - expected int8");
//   Serial.print("[LOG] Output dtype: ");
//   Serial.println(tfl_output->type == kTfLiteInt8 ? "int8 (correct)" : "WRONG - expected int8");

//   Serial.print("[LOG] Input shape:  [");
//   for (int i = 0; i < tfl_input->dims->size; i++) {
//     Serial.print(tfl_input->dims->data[i]);
//     if (i < tfl_input->dims->size - 1) Serial.print(", ");
//   }
//   Serial.println("]  (expected [1, 200, 6])");

//   Serial.print("[LOG] Arena used:   ");
//   Serial.print(tfl_interpreter->arena_used_bytes() / 1024);
//   Serial.println(" KB");

//   Serial.println("[LOG] Ready - collecting samples...");
//   Serial.println("==============================");

  memset(sample_buf, 0, sizeof(sample_buf));
  last_sample_us = micros();
}

// ---------------------------------------------------------------------------
// Loop
// ---------------------------------------------------------------------------

void loop() {
  unsigned long now = micros();
  if (now - last_sample_us < SAMPLE_INTERVAL_US) return;
  last_sample_us += SAMPLE_INTERVAL_US;

  // --- Read IMU ---
  sensors_event_t accel_evt, gyro_evt, temp_evt;
  imu.getEvent(&accel_evt, &gyro_evt, &temp_evt);

  // Match training units: m/s2 -> g,  rad/s -> deg/s
  float ax = accel_evt.acceleration.x / 9.81f;
  float ay = accel_evt.acceleration.y / 9.81f;
  float az = accel_evt.acceleration.z / 9.81f;
  float gx = gyro_evt.gyro.x * 57.2958f;
  float gy = gyro_evt.gyro.y * 57.2958f;
  float gz = gyro_evt.gyro.z * 57.2958f;

  // Cache for the debug print in run_inference()
  last_ax = ax; last_ay = ay; last_az = az;
  last_gx = gx; last_gy = gy; last_gz = gz;

  // --- Store in circular buffer ---
  sample_buf[buf_head][0] = ax;
  sample_buf[buf_head][1] = ay;
  sample_buf[buf_head][2] = az;
  sample_buf[buf_head][3] = gx;
  sample_buf[buf_head][4] = gy;
  sample_buf[buf_head][5] = gz;

  buf_head = (buf_head + 1) % WINDOW_LENGTH;
  if (samples_in_buf < WINDOW_LENGTH) samples_in_buf++;
  samples_since_last_inference++;

  // --- Inference every STRIDE samples once the buffer is full ---
  if (samples_in_buf == WINDOW_LENGTH &&
      samples_since_last_inference >= STRIDE) {
    samples_since_last_inference = 0;
    run_inference();
  }
}





// #include <Arduino.h>
// #include <Wire.h>
// #include <Adafruit_LSM6DSOX.h>

// #include <TensorFlowLite_ESP32.h>
// #include "tensorflow/lite/micro/all_ops_resolver.h"
// #include "tensorflow/lite/micro/micro_error_reporter.h"
// #include "tensorflow/lite/micro/micro_interpreter.h"
// #include "tensorflow/lite/schema/schema_generated.h"

// #include "model_data.h"

// // ============================================================================
// // CONFIG
// // ============================================================================

// const int WINDOW_LENGTH = 200;
// const int NUM_CHANNELS = 6;
// const int STRIDE = 100;

// const float STITCH_THRESHOLD = 0.5f;
// const float RESET_THRESHOLD = 0.3f;    // Prob must drop below this to re-arm
// const int DEBUG_INTERVAL = 50;         // Print sensor data every N samples

// // ============================================================================
// // GLOBALS
// // ============================================================================

// Adafruit_LSM6DSOX imu;

// float window_buffer[WINDOW_LENGTH * NUM_CHANNELS];
// int buffer_index = 0;
// int sample_count = 0;
// int total_samples = 0;
// bool buffer_filled = false;
// bool armed = true;

// unsigned long last_sample_time = 0;
// unsigned long stitch_count = 0;

// alignas(16) uint8_t tensor_arena[80 * 1024];
// tflite::MicroInterpreter* interpreter = nullptr;
// TfLiteTensor* input_tensor = nullptr;
// TfLiteTensor* output_tensor = nullptr;

// // ============================================================================
// // SETUP
// // ============================================================================

// void setup() {
//     Serial.begin(115200);
//     delay(1000);
    
//     Serial.println("\n================================");
//     Serial.println("Crochet Stitch Counter");
//     Serial.println("No Filter - Raw Data Model");
//     Serial.println("================================\n");
    
//     // Init I2C
//     Wire.begin();
//     Wire.setClock(100000);
    
//     // Init sensor
//     Serial.print("Sensor: ");
//     while (!imu.begin_I2C()) {
//         Serial.print(".");
//         delay(500);
//     }
//     Serial.println("OK");
    
//     imu.setAccelRange(LSM6DS_ACCEL_RANGE_2_G);
//     imu.setGyroRange(LSM6DS_GYRO_RANGE_250_DPS);
//     imu.setAccelDataRate(LSM6DS_RATE_104_HZ);
//     imu.setGyroDataRate(LSM6DS_RATE_104_HZ);
    
//     // Init model
//     Serial.print("Model: ");
    
//     static tflite::MicroErrorReporter micro_error;
//     static tflite::AllOpsResolver resolver;
//     const tflite::Model* model = tflite::GetModel(model_data);
    
//     static tflite::MicroInterpreter static_interpreter(
//         model, resolver, tensor_arena, sizeof(tensor_arena), &micro_error
//     );
//     interpreter = &static_interpreter;
//     interpreter->AllocateTensors();
    
//     input_tensor = interpreter->input(0);
//     output_tensor = interpreter->output(0);
    
//     Serial.println("OK");
    
//     // Print quantization info
//     Serial.println("\nQuantization:");
//     Serial.print("  Input scale: ");
//     Serial.print(input_tensor->params.scale, 4);
//     Serial.print(" zp: ");
//     Serial.println(input_tensor->params.zero_point);
//     Serial.print("  Output scale: ");
//     Serial.print(output_tensor->params.scale, 6);
//     Serial.print(" zp: ");
//     Serial.println(output_tensor->params.zero_point);
    
//     Serial.println("\nConfig:");
//     Serial.print("  Threshold: ");
//     Serial.println(STITCH_THRESHOLD);
//     Serial.print("  Reset: ");
//     Serial.println(RESET_THRESHOLD);
    
//     Serial.println("\n>>> Ready! Start crocheting...\n");
// }

// // ============================================================================
// // LOOP
// // ============================================================================

// void loop() {
//     // Sample at 100Hz (every 10ms)
//     if (millis() - last_sample_time >= 10) {
//         last_sample_time = millis();
        
//         // Read sensor
//         sensors_event_t accel, gyro, temp;
//         imu.getEvent(&accel, &gyro, &temp);
        
//         // Convert units (MUST match training data collection!)
//         // Accelerometer: m/s² -> g
//         // Gyroscope: rad/s -> °/s
//         float ax = accel.acceleration.x / 9.81f;
//         float ay = accel.acceleration.y / 9.81f;
//         float az = accel.acceleration.z / 9.81f;
//         float gx = gyro.gyro.x * 57.2958f;
//         float gy = gyro.gyro.y * 57.2958f;
//         float gz = gyro.gyro.z * 57.2958f;
        
//         // Debug: print sensor values periodically
//         if (total_samples % DEBUG_INTERVAL == 0) {
//             Serial.print("[");
//             Serial.print(total_samples);
//             Serial.print("] ax=");
//             Serial.print(ax, 2);
//             Serial.print(" ay=");
//             Serial.print(ay, 2);
//             Serial.print(" az=");
//             Serial.print(az, 2);
//             Serial.print(" | gx=");
//             Serial.print(gx, 1);
//             Serial.print(" gy=");
//             Serial.print(gy, 1);
//             Serial.print(" gz=");
//             Serial.println(gz, 1);
//         }
        
//         total_samples++;
        
//         // Store in circular buffer
//         int idx = buffer_index * NUM_CHANNELS;
//         window_buffer[idx + 0] = ax;
//         window_buffer[idx + 1] = ay;
//         window_buffer[idx + 2] = az;
//         window_buffer[idx + 3] = gx;
//         window_buffer[idx + 4] = gy;
//         window_buffer[idx + 5] = gz;
        
//         buffer_index = (buffer_index + 1) % WINDOW_LENGTH;
//         sample_count++;
        
//         // Check if buffer filled (first 2 seconds)
//         if (!buffer_filled && buffer_index == 0) {
//             buffer_filled = true;
//             Serial.println("\n[INFO] Buffer ready, starting inference\n");
//         }
        
//         // Run inference every STRIDE samples (1 second)
//         if (buffer_filled && sample_count >= STRIDE) {
//             sample_count = 0;
            
//             // Get quantization parameters from model
//             float input_scale = input_tensor->params.scale;
//             int input_zp = input_tensor->params.zero_point;
//             int8_t* input_data = input_tensor->data.int8;
            
//             // Copy and quantize window data to input tensor
//             for (int i = 0; i < WINDOW_LENGTH; i++) {
//                 // Read from circular buffer in correct order (oldest first)
//                 int src = ((buffer_index + i) % WINDOW_LENGTH) * NUM_CHANNELS;
//                 int dst = i * NUM_CHANNELS;
                
//                 for (int ch = 0; ch < NUM_CHANNELS; ch++) {
//                     float val = window_buffer[src + ch];
                    
//                     // Quantize: q = round(val / scale) + zero_point
//                     int32_t q = (int32_t)roundf(val / input_scale) + input_zp;
                    
//                     // Clamp to int8 range
//                     if (q > 127) q = 127;
//                     if (q < -128) q = -128;
                    
//                     input_data[dst + ch] = (int8_t)q;
//                 }
//             }
            
//             // Run inference
//             interpreter->Invoke();
            
//             // Get output and dequantize
//             int8_t out_q = output_tensor->data.int8[0];
//             float output_scale = output_tensor->params.scale;
//             int output_zp = output_tensor->params.zero_point;
            
//             // Dequantize: val = (q - zero_point) * scale
//             float prob = (out_q - output_zp) * output_scale;
            
//             // Clamp to [0, 1]
//             if (prob < 0) prob = 0;
//             if (prob > 1) prob = 1;
            
//             // State machine: re-arm after prob drops
//             if (!armed && prob < RESET_THRESHOLD) {
//                 armed = true;
//             }
            
//             // Print result
//             Serial.print(">>> Prob: ");
//             Serial.print(prob, 3);
//             Serial.print(" | Armed: ");
//             Serial.print(armed ? "Y" : "N");
            
//             // Check for stitch
//             if (prob > STITCH_THRESHOLD && armed) {
//                 stitch_count++;
//                 armed = false;  // Prevent duplicate counts
                
//                 Serial.print(" | STITCH #");
//                 Serial.print(stitch_count);
//             }
            
//             Serial.println();
//         }
//     }
// }

// sorta worky

// #include <Arduino.h>
// #include <Adafruit_ISM330DHCX.h>
// #include <Adafruit_Sensor.h>
// #include <Wire.h>
// #include "model_data.h"

// #include <TensorFlowLite_ESP32.h>
// #include "tensorflow/lite/micro/micro_interpreter.h"
// #include "tensorflow/lite/micro/micro_mutable_op_resolver.h"
// #include "tensorflow/lite/micro/micro_error_reporter.h"
// #include "tensorflow/lite/schema/schema_generated.h"

// // ─── Model settings (must match your Python config) ────────────────────────────
// const int   WINDOW_LENGTH  = 200;
// const int   NUM_CHANNELS   = 6;
// const int   STRIDE         = 100;
// const float THRESHOLD      = 0.5f;

// // ─── TFLite globals ─────────────────────────────────────────────────────────────
// const int TENSOR_ARENA_SIZE = 64 * 1024;
// uint8_t tensor_arena[TENSOR_ARENA_SIZE];

// static tflite::MicroErrorReporter micro_error_reporter;
// tflite::ErrorReporter*            error_reporter = &micro_error_reporter;

// const tflite::Model*         tfl_model     = nullptr;
// tflite::MicroInterpreter*    interpreter   = nullptr;
// TfLiteTensor*                input_tensor  = nullptr;
// TfLiteTensor*                output_tensor = nullptr;

// // ─── Sensor ─────────────────────────────────────────────────────────────────────
// Adafruit_LSM6DSOX lsm;

// const int           SAMPLE_RATE_HZ     = 100;
// const unsigned long SAMPLE_INTERVAL_MS = 1000 / SAMPLE_RATE_HZ;
// unsigned long       lastSampleTime     = 0;

// // ─── Sliding window buffer ───────────────────────────────────────────────────────
// float window_buf[WINDOW_LENGTH][NUM_CHANNELS];
// int   sample_count = 0;
// int   buf_head     = 0;

// // ─── Stitch counter ──────────────────────────────────────────────────────────────
// int stitch_count = 0;


// void setup() {
//     Serial.begin(115200);
//     delay(2000);
//     Serial.println("=== Crochet Stitch Detector ==="); Serial.flush();

//     // ── Init IMU ──────────────────────────────────────────────────────────────────
//     while (!lsm.begin_I2C()) {
//         Serial.println("[WARN] LSM6DSOX not found, retrying...");
//         delay(1000);
//     }

//     lsm.setAccelRange(LSM6DS_ACCEL_RANGE_2_G);
//     lsm.setGyroRange(LSM6DS_GYRO_RANGE_250_DPS);
//     lsm.setAccelDataRate(LSM6DS_RATE_104_HZ);
//     lsm.setGyroDataRate(LSM6DS_RATE_104_HZ);
//     Serial.println("[OK] IMU ready"); Serial.flush();

//     // ── Load TFLite model ─────────────────────────────────────────────────────────
//     tfl_model = tflite::GetModel(model_data);
//     if (tfl_model->version() != TFLITE_SCHEMA_VERSION) {
//         Serial.println("[ERROR] Model schema mismatch"); Serial.flush();
//         while (1) delay(10);
//     }

//     static tflite::MicroMutableOpResolver<13> resolver;
//     resolver.AddConv2D();
//     resolver.AddDepthwiseConv2D();
//     resolver.AddFullyConnected();
//     resolver.AddMean();
//     resolver.AddRelu();
//     resolver.AddLogistic();
//     resolver.AddReshape();
//     resolver.AddMaxPool2D();
//     resolver.AddSub(); 
//     resolver.AddMul(); 
//     resolver.AddAdd(); 
//     resolver.AddExpandDims();     


//     static tflite::MicroInterpreter static_interpreter(
//         tfl_model, resolver, tensor_arena, TENSOR_ARENA_SIZE, error_reporter
//     );
//     interpreter = &static_interpreter;

//     if (interpreter->AllocateTensors() != kTfLiteOk) {
//         Serial.println("[ERROR] AllocateTensors failed — try increasing TENSOR_ARENA_SIZE"); Serial.flush();
//         while (1) delay(10);
//     }

//     // Serial.print("Input tensor type: ");
//     // Serial.println(input_tensor->type);

//     input_tensor  = interpreter->input(0);
//     output_tensor = interpreter->output(0);

//     Serial.println("[OK] Model loaded"); Serial.flush();
//     Serial.println("Listening for stitches..."); Serial.flush();
// }

// void run_inference() {
//     // Copy circular buffer into input tensor in chronological order
//     for (int t = 0; t < WINDOW_LENGTH; t++) {
//         int buf_idx = (buf_head + t) % WINDOW_LENGTH;
//         for (int c = 0; c < NUM_CHANNELS; c++) {
//             input_tensor->data.f[t * NUM_CHANNELS + c] = window_buf[buf_idx][c];
//         }
//     }

//     if (interpreter->Invoke() != kTfLiteOk) {
//         Serial.println("[ERROR] Inference failed");
//         return;
//     }

//     float score = output_tensor->data.f[0];
//     bool stitch = score >= THRESHOLD;

//     if (stitch) stitch_count++;
//     else if (stitch_count > 0) stitch_count--;

//     Serial.print("Score: ");
//     Serial.print(score, 4);
//     Serial.print("  ->  ");
//     Serial.print(stitch ? "STITCH" : "non-stitch");
//     Serial.print("  |  Stitch count: ");
//     Serial.println(stitch_count);
// }

// void loop() {
//     if (millis() - lastSampleTime < SAMPLE_INTERVAL_MS) return;
//     lastSampleTime = millis();

//     // Read IMU
//     sensors_event_t accel, gyro, temp;
//     lsm.getEvent(&accel, &gyro, &temp);

//     // Apply normalization from training
//     float mean[NUM_CHANNELS] = {-0.16766436, -0.6738868, 0.10534707, -0.2586711, 1.0771587, 0.82292694};
//     float std[NUM_CHANNELS]  = {0.2754282, 0.34008133, 0.59101254, 69.39195, 40.35763, 40.63095};

//     window_buf[buf_head][0] = (accel.acceleration.x / 9.81f - mean[0]) / std[0];
//     window_buf[buf_head][1] = (accel.acceleration.y / 9.81f - mean[1]) / std[1];
//     window_buf[buf_head][2] = (accel.acceleration.z / 9.81f - mean[2]) / std[2];
//     window_buf[buf_head][3] = (gyro.gyro.x * 57.2958f - mean[3]) / std[3];
//     window_buf[buf_head][4] = (gyro.gyro.y * 57.2958f - mean[4]) / std[4];
//     window_buf[buf_head][5] = (gyro.gyro.z * 57.2958f - mean[5]) / std[5];

//     // Advance circular buffer
//     buf_head = (buf_head + 1) % WINDOW_LENGTH;
//     sample_count++;

//     // Run inference every STRIDE samples
//     if (sample_count >= WINDOW_LENGTH && (sample_count % STRIDE) == 0) {
//         run_inference();
//     }
// }











// #include <Arduino.h>
// #include <Wire.h>
// #include <Adafruit_Sensor.h>
// #include <Adafruit_BNO055.h>

// Adafruit_BNO055 bno = Adafruit_BNO055(55);

// const int SAMPLE_RATE_HZ = 100;
// const unsigned long SAMPLE_INTERVAL_MS = 1000 / SAMPLE_RATE_HZ;

// unsigned long lastSampleTime = 0;
// unsigned long startTime = 0;

// void setup(void)
// {
//   Serial.begin(115200);
//   delay(2000);

//   Serial.println("==============================");
//   Serial.println("BNO055 Motion Data Logger");
//   Serial.println("==============================");

//   Serial.print("[LOG] Initializing BNO055... ");

//   if (!bno.begin())
//   {
//     Serial.println("[ERROR] Failed to find BNO055");
//     while (1) delay(10);
//   }

//   Serial.println("OK");

//   delay(1000);

//   bno.setExtCrystalUse(true);

//   Serial.println("[LOG] BNO055 Ready");
//   Serial.println("==============================");

//   bno.setMode(OPERATION_MODE_IMUPLUS);

//   startTime = millis();
// }

// void loop()
// {
  
//   if (millis() - lastSampleTime >= SAMPLE_INTERVAL_MS)
//   {
//     lastSampleTime = millis();

//     // Raw accelerometer
//     imu::Vector<3> accel = bno.getVector(Adafruit_BNO055::VECTOR_ACCELEROMETER);

//     // Raw gyroscope
//     imu::Vector<3> gyro = bno.getVector(Adafruit_BNO055::VECTOR_GYROSCOPE);

//     float ax = accel.x() / 9.81;
//     float ay = accel.y() / 9.81;
//     float az = accel.z() / 9.81;

//     float gx = gyro.x();
//     float gy = gyro.y();
//     float gz = gyro.z();

//     float accel_mag = sqrt(ax*ax + ay*ay + az*az);
//     float gyro_mag  = sqrt(gx*gx + gy*gy + gz*gz);

//     unsigned long timestamp = millis() - startTime;

//     Serial.print(timestamp);
//     Serial.print(",");

//     Serial.print(ax,4);
//     Serial.print(",");
//     Serial.print(ay,4);
//     Serial.print(",");
//     Serial.print(az,4);
//     Serial.print(",");

//     Serial.print(gx,2);
//     Serial.print(",");
//     Serial.print(gy,2);
//     Serial.print(",");
//     Serial.print(gz,2);
//     Serial.print(",");

//     Serial.print(accel_mag,4);
//     Serial.print(",");
//     Serial.println(gyro_mag,2);
//   }
// }




// ========================================================================================


//// WORKING 

// #include <Arduino.h>
// #include <Adafruit_ISM330DHCX.h>
// #include <Adafruit_Sensor.h>
// #include <Wire.h>

// Adafruit_LSM6DSOX lsmdsox;

// lsm6ds_accel_range_t _ACCEL_RANGE = LSM6DS_ACCEL_RANGE_2_G;
// lsm6ds_gyro_range_t  _GYRO_RANGE  = LSM6DS_GYRO_RANGE_250_DPS;
// lsm6ds_data_rate_t   _DATA_RATE   = LSM6DS_RATE_104_HZ;

// const int SAMPLE_RATE_HZ = 100;
// const unsigned long SAMPLE_INTERVAL_MS = 1000 / SAMPLE_RATE_HZ;
// unsigned long lastSampleTime = 0;
// unsigned long startTime = 0;

// // Function prototype
// void print_sensor_settings();

// void setup(void) {
//   Serial.begin(115200);

//   while (!Serial) delay(10);

//   Serial.println("==============================");
//   Serial.println("Crochet Motion Data Logger");
//   Serial.println("==============================");

//   Serial.print("[LOG] Initializing LSM6DSOX... ");

//   if (!lsmdsox.begin_I2C()) {
//     Serial.println("[ERROR] Failed to find LSM6DSOX chip");
//     while (1) delay(10);
//   }
//   Serial.println("OK");

//   Serial.print("[LOG] Configuring LSM6DSOX... ");
//   lsmdsox.setAccelRange(_ACCEL_RANGE);
//   lsmdsox.setGyroRange(_GYRO_RANGE);
//   lsmdsox.setAccelDataRate(_DATA_RATE);
//   lsmdsox.setGyroDataRate(_DATA_RATE);
//   Serial.println("OK");

//   Serial.println("[LOG] LSM6DSOX Settings:");
//   print_sensor_settings();

//   Serial.println("[LOG] LSM6DSOX Ready");
//   Serial.println("==============================");

//   delay(1000);

//   startTime = millis();
// }

// void loop() {
//   if (millis() - lastSampleTime >= SAMPLE_INTERVAL_MS) {
//     lastSampleTime = millis();

//     sensors_event_t accel, gyro, temp;
//     lsmdsox.getEvent(&accel, &gyro, &temp);

//     // Accelerometer (m/s² to g)
//     float ax = accel.acceleration.x / 9.81;
//     float ay = accel.acceleration.y / 9.81;
//     float az = accel.acceleration.z / 9.81;

//     // Gyroscope (rad/s to °/s)
//     float gx = gyro.gyro.x * 57.2958;
//     float gy = gyro.gyro.y * 57.2958;
//     float gz = gyro.gyro.z * 57.2958;

//     // Calculate magnitudes
//     float accel_mag = sqrt(ax*ax + ay*ay + az*az);
//     float gyro_mag  = sqrt(gx*gx + gy*gy + gz*gz);

//     unsigned long timestamp = millis() - startTime;

//     // debugPrint(timestamp, ax, ay, az, gx, gy, gz, accel_mag, gyro_mag);

//     // Output CSV line
//     Serial.print(timestamp);
//     Serial.print(",");
//     Serial.print(ax, 4);
//     Serial.print(",");
//     Serial.print(ay, 4);
//     Serial.print(",");
//     Serial.print(az, 4);
//     Serial.print(",");
//     Serial.print(gx, 2);
//     Serial.print(",");
//     Serial.print(gy, 2);
//     Serial.print(",");
//     Serial.print(gz, 2);
//     Serial.print(",");
//     Serial.print(accel_mag, 4);
//     Serial.print(",");
//     Serial.println(gyro_mag, 2);
//   }
// }

// void print_sensor_settings() {
//   Serial.print("  Accelerometer range: ");
//   switch (lsmdsox.getAccelRange()) {
//     case LSM6DS_ACCEL_RANGE_2_G:  Serial.println("±2G");  break;
//     case LSM6DS_ACCEL_RANGE_4_G:  Serial.println("±4G");  break;
//     case LSM6DS_ACCEL_RANGE_8_G:  Serial.println("±8G");  break;
//     case LSM6DS_ACCEL_RANGE_16_G: Serial.println("±16G"); break;
//   }

//   Serial.print("  Gyroscope range:     ");
//   switch (lsmdsox.getGyroRange()) {
//     case LSM6DS_GYRO_RANGE_125_DPS:  Serial.println("±125°/s");  break;
//     case LSM6DS_GYRO_RANGE_250_DPS:  Serial.println("±250°/s");  break;
//     case LSM6DS_GYRO_RANGE_500_DPS:  Serial.println("±500°/s");  break;
//     case LSM6DS_GYRO_RANGE_1000_DPS: Serial.println("±1000°/s"); break;
//     case LSM6DS_GYRO_RANGE_2000_DPS: Serial.println("±2000°/s"); break;
//     case ISM330DHCX_GYRO_RANGE_4000_DPS: Serial.println("±4000°/s"); break;
//   }

//   Serial.print("  Accel data rate:     ");
//   switch (lsmdsox.getAccelDataRate()) {
//     case LSM6DS_RATE_SHUTDOWN:  Serial.println("Shutdown");    break;
//     case LSM6DS_RATE_12_5_HZ:  Serial.println("12.5 Hz");     break;
//     case LSM6DS_RATE_26_HZ:    Serial.println("26 Hz");       break;
//     case LSM6DS_RATE_52_HZ:    Serial.println("52 Hz");       break;
//     case LSM6DS_RATE_104_HZ:   Serial.println("104 Hz");      break;
//     case LSM6DS_RATE_208_HZ:   Serial.println("208 Hz");      break;
//     case LSM6DS_RATE_416_HZ:   Serial.println("416 Hz");      break;
//     case LSM6DS_RATE_833_HZ:   Serial.println("833 Hz");      break;
//     case LSM6DS_RATE_1_66K_HZ: Serial.println("1.66 KHz");    break;
//     case LSM6DS_RATE_3_33K_HZ: Serial.println("3.33 KHz");    break;
//     case LSM6DS_RATE_6_66K_HZ: Serial.println("6.66 KHz");    break;
//   }

//   Serial.print("  Gyro data rate:      ");
//   switch (lsmdsox.getGyroDataRate()) {
//     case LSM6DS_RATE_SHUTDOWN:  Serial.println("Shutdown");    break;
//     case LSM6DS_RATE_12_5_HZ:  Serial.println("12.5 Hz");     break;
//     case LSM6DS_RATE_26_HZ:    Serial.println("26 Hz");       break;
//     case LSM6DS_RATE_52_HZ:    Serial.println("52 Hz");       break;
//     case LSM6DS_RATE_104_HZ:   Serial.println("104 Hz");      break;
//     case LSM6DS_RATE_208_HZ:   Serial.println("208 Hz");      break;
//     case LSM6DS_RATE_416_HZ:   Serial.println("416 Hz");      break;
//     case LSM6DS_RATE_833_HZ:   Serial.println("833 Hz");      break;
//     case LSM6DS_RATE_1_66K_HZ: Serial.println("1.66 KHz");    break;
//     case LSM6DS_RATE_3_33K_HZ: Serial.println("3.33 KHz");    break;
//     case LSM6DS_RATE_6_66K_HZ: Serial.println("6.66 KHz");    break;
//   }
// }


























// void debugPrint(
//   unsigned long timestamp,
//   float ax, float ay, float az,
//   float gx, float gy, float gz,
//   float accel_mag, float gyro_mag
// ) {
//   Serial.println("----- SENSOR DEBUG -----");

//   Serial.print("Time (ms): ");
//   Serial.println(timestamp);

//   Serial.println("Accelerometer (g):");
//   Serial.print("  X: "); Serial.println(ax, 4);
//   Serial.print("  Y: "); Serial.println(ay, 4);
//   Serial.print("  Z: "); Serial.println(az, 4);

//   Serial.println("Gyroscope (deg/s):");
//   Serial.print("  X: "); Serial.println(gx, 2);
//   Serial.print("  Y: "); Serial.println(gy, 2);
//   Serial.print("  Z: "); Serial.println(gz, 2);

//   Serial.print("Accel Magnitude: ");
//   Serial.println(accel_mag, 4);

//   Serial.print("Gyro Magnitude: ");
//   Serial.println(gyro_mag, 2);

//   Serial.println("------------------------");
//   Serial.println();
// }



// ========================================================================================


// #include <Arduino.h>
// #include <Adafruit_MPU6050.h>
// #include <Adafruit_Sensor.h>
// #include <Wire.h>

// Adafruit_MPU6050 mpu;

// mpu6050_accel_range_t _ACCEL_RANGE = MPU6050_RANGE_2_G;
// mpu6050_gyro_range_t _GYRO_RANGE = MPU6050_RANGE_250_DEG;
// mpu6050_bandwidth_t _BANDWIDTH = MPU6050_BAND_21_HZ;

// // ADD THESE MISSING VARIABLES:
// const int SAMPLE_RATE_HZ = 100;
// const unsigned long SAMPLE_INTERVAL_MS = 1000 / SAMPLE_RATE_HZ;  // = 10ms
// unsigned long lastSampleTime = 0;
// unsigned long startTime = 0;

// // Function prototype
// void print_sensor_settings();

// void setup(void) {
//   Serial.begin(115200);

//   while (!Serial) delay(10);

//   Serial.println("==============================");
//   Serial.println("Crochet Motion Data Logger");
//   Serial.println("==============================");

//   Serial.print("[LOG] Initializing MPU6050... ");

//   if (!mpu.begin()) {
//     Serial.println("[ERROR] Failed to find MPU6050 chip");
//     while (1) delay(10);
//   }
//   Serial.println("OK");

//   Serial.print("[LOG] Configuring MPU6050... ");
//   mpu.setAccelerometerRange(_ACCEL_RANGE);
//   mpu.setGyroRange(_GYRO_RANGE);
//   mpu.setFilterBandwidth(_BANDWIDTH);
//   Serial.println("OK");

//   Serial.println("[LOG] MPU6050 Settings:");
//   print_sensor_settings();

//   Serial.println("[LOG] MPU6050 Ready");
//   Serial.println("==============================");

//   delay(1000);
  
//   startTime = millis();
// }

// void loop() {
//   if (millis() - lastSampleTime >= SAMPLE_INTERVAL_MS) {
//     lastSampleTime = millis();
    
//     // Get sensor events
//     sensors_event_t accel, gyro, temp;
//     mpu.getEvent(&accel, &gyro, &temp);
    
//     // Accelerometer (m/s² to g)
//     float ax = accel.acceleration.x / 9.81;
//     float ay = accel.acceleration.y / 9.81;
//     float az = accel.acceleration.z / 9.81;
    
//     // Gyroscope (rad/s to °/s)
//     float gx = gyro.gyro.x * 57.2958;
//     float gy = gyro.gyro.y * 57.2958;
//     float gz = gyro.gyro.z * 57.2958;
    
//     // Calculate magnitudes
//     float accel_mag = sqrt(ax*ax + ay*ay + az*az);
//     float gyro_mag = sqrt(gx*gx + gy*gy + gz*gz);
    
//     unsigned long timestamp = millis() - startTime;
    
//     // Output CSV line
//     Serial.print(timestamp);
//     Serial.print(",");
//     Serial.print(ax, 4);
//     Serial.print(",");
//     Serial.print(ay, 4);
//     Serial.print(",");
//     Serial.print(az, 4);
//     Serial.print(",");
//     Serial.print(gx, 2);
//     Serial.print(",");
//     Serial.print(gy, 2);
//     Serial.print(",");
//     Serial.print(gz, 2);
//     Serial.print(",");
//     Serial.print(accel_mag, 4);
//     Serial.print(",");
//     Serial.println(gyro_mag, 2);
//   }
// }

// void print_sensor_settings() {
//   Serial.print("       Accelerometer range: ");
//   switch (mpu.getAccelerometerRange()) {
//     case MPU6050_RANGE_2_G:  Serial.println("±2G");  break;
//     case MPU6050_RANGE_4_G:  Serial.println("±4G");  break;
//     case MPU6050_RANGE_8_G:  Serial.println("±8G");  break;
//     case MPU6050_RANGE_16_G: Serial.println("±16G"); break;
//   }
  
//   Serial.print("       Gyroscope range: ");
//   switch (mpu.getGyroRange()) {
//     case MPU6050_RANGE_250_DEG:  Serial.println("±250°/s");  break;
//     case MPU6050_RANGE_500_DEG:  Serial.println("±500°/s");  break;
//     case MPU6050_RANGE_1000_DEG: Serial.println("±1000°/s"); break;
//     case MPU6050_RANGE_2000_DEG: Serial.println("±2000°/s"); break;
//   }
  
//   Serial.print("       Filter bandwidth: ");
//   switch (mpu.getFilterBandwidth()) {
//     case MPU6050_BAND_260_HZ: Serial.println("260 Hz"); break;
//     case MPU6050_BAND_184_HZ: Serial.println("184 Hz"); break;
//     case MPU6050_BAND_94_HZ:  Serial.println("94 Hz");  break;
//     case MPU6050_BAND_44_HZ:  Serial.println("44 Hz");  break;
//     case MPU6050_BAND_21_HZ:  Serial.println("21 Hz");  break;
//     case MPU6050_BAND_10_HZ:  Serial.println("10 Hz");  break;
//     case MPU6050_BAND_5_HZ:   Serial.println("5 Hz");   break;
//   }
// }